// example/react/src/components/TodoInput.tsx
import { useState } from "react";
import { TextField } from "./TextField";
import { AddButton } from "./AddButton";

interface TodoInputProps {
  onAdd: (text: string) => void;
}

/** Input field with a submit button for creating new todos. */
export function TodoInput({ onAdd }: TodoInputProps) {
  const [value, setValue] = useState("");

  /** Handles form submission – trims input and resets the field. */
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const trimmed = value.trim();
    if (!trimmed) return;
    onAdd(trimmed);
    setValue("");
  };

  return (
    <form onSubmit={handleSubmit} style={styles.form}>
      <TextField
        value={value}
        onChange={(e) => setValue(e.target.value)}
        placeholder="What needs to be done?"
      />
      <AddButton />
    </form>
  );
}

const styles: Record<string, React.CSSProperties> = {
  form: {
    display: "flex",
    gap: 8,
  },
};

// example/angular/src/app/todo-input.component.ts
import { Component, output, signal } from "@angular/core";
import { CommonModule } from "@angular/common";
import { TextFieldComponent } from "./text-field.component";
import { AddButtonComponent } from "./add-button.component";

/** Input field with a submit button for creating new todos. */
@Component({
  selector: "app-todo-input",
  standalone: true,
  imports: [CommonModule, TextFieldComponent, AddButtonComponent],
  template: `
    <form (submit)="handleSubmit($event)" [ngStyle]="styles.form">
      <app-text-field
        [value]="value()"
        (valueChange)="value.set($event)"
        placeholder="What needs to be done?"
      />
      <app-add-button />
    </form>
  `,
})
export class TodoInputComponent {
  value = signal("");
  add = output<string>();

  /** Handles form submission – trims input and resets the field. */
  handleSubmit(e: Event): void {
    e.preventDefault();
    const trimmed = this.value().trim();
    if (!trimmed) return;
    this.add.emit(trimmed);
    this.value.set("");
  }

  styles = {
    form: {
      display: "flex",
      gap: "8px",
    },
  };
}
